image: "archlinux:latest"

stages:
  - build

build-linux-x64:
  stage: build
  before_script:
    - pacman-key --init
    - pacman -Syu --needed --noconfirm ninja cmake gcc gcc-libs glibc frameworkintegration gcc-libs glibc kcmutils kcolorscheme kconfig kcoreaddons kdecoration kguiaddons ki18n kiconthemes kirigami kwidgetsaddons kwindowsystem qt6-base qt6-declarative qt6-svg extra-cmake-modules kwin kdoctools krunner plasma-wayland-protocols wayland wayland-protocols python pkgconf vulkan-headers
  script:
    - cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=ON -B build .
    - cmake --build build 
    - DESTDIR=out cmake --install build
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 6 mos
    paths: 
      - out/
